# frml_lexer.py.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.4'
_lextokens    = {'ID': 1, 'NUMBER': 1, 'LPAREN': 1, 'RPAREN': 1, 'NOT': 1, 'AND': 1, 'OR': 1, 'IMP': 1, 'IFF': 1, 'EQ': 1, 'NOT_EQ': 1, 'COLON': 1, 'COMMA': 1, 'INN': 1, 'GR': 1, 'LS': 1, 'GRE': 1, 'LSE': 1, 'STAR': 1, 'POWER': 1, 'DIV': 1, 'ADD': 1, 'MINUS': 1, 'BAR': 1, 'LBRACKET': 1, 'RBRACKET': 1, 'PRIME': 1, 'SEMI': 1, 'TRANSPOSE': 1, 'DOMR': 1, 'RANR': 1, 'DOMS': 1, 'RANS': 1, 'OVER': 1, 'LIMAGE': 1, 'RIMAGE': 1, 'LNCB': 1, 'RNCB': 1, 'BOTTOM': 1, 'TOP': 1, 'FORALL': 1, 'EXISTS': 1, 'SUB': 1, 'SUBE': 1, 'IN': 1, 'UNION': 1, 'INTERSECTION': 1, 'DOMAIN': 1, 'RANGE': 1}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [("(?P<t_ID>[a-zA-Z_][a-zA-Z_0-9\\']*[!\\?]?)|(?P<t_NUMBER>[0-9]+)|(?P<t_newline>\\n+)|(?P<t_comment>%[^\\n]*\\n?)|(?P<t_OVER>\\(\\+\\))|(?P<t_DOMS><\\-\\|)|(?P<t_RANS>\\|\\->)|(?P<t_BAR>\\|\\|)|(?P<t_LIMAGE>\\(\\|)|(?P<t_RIMAGE>\\|\\))|(?P<t_IFF><=>)|(?P<t_DOMR><\\|)|(?P<t_RANR>\\|>)|(?P<t_LPAREN>\\()|(?P<t_RPAREN>\\))|(?P<t_OR>\\|)|(?P<t_IMP>=>)|(?P<t_EQ>==)|(?P<t_NOT_EQ>!=)|(?P<t_COLON>\\.)|(?P<t_GRE>>=)|(?P<t_LSE><=)|(?P<t_STAR>\\*)|(?P<t_POWER>\\^)|(?P<t_ADD>\\+)|(?P<t_MINUS>\\-)|(?P<t_LBRACKET>\\{)|(?P<t_RBRACKET>\\})|(?P<t_LNCB>\\[)|(?P<t_RNCB>\\])|(?P<t_NOT>!)|(?P<t_AND>&)|(?P<t_COMMA>,)|(?P<t_INN>:)|(?P<t_GR>>)|(?P<t_LS><)|(?P<t_DIV>/)|(?P<t_PRIME>')|(?P<t_SEMI>;)|(?P<t_TRANSPOSE>~)", [None, ('t_ID', 'ID'), ('t_NUMBER', 'NUMBER'), ('t_newline', 'newline'), ('t_comment', 'comment'), (None, 'OVER'), (None, 'DOMS'), (None, 'RANS'), (None, 'BAR'), (None, 'LIMAGE'), (None, 'RIMAGE'), (None, 'IFF'), (None, 'DOMR'), (None, 'RANR'), (None, 'LPAREN'), (None, 'RPAREN'), (None, 'OR'), (None, 'IMP'), (None, 'EQ'), (None, 'NOT_EQ'), (None, 'COLON'), (None, 'GRE'), (None, 'LSE'), (None, 'STAR'), (None, 'POWER'), (None, 'ADD'), (None, 'MINUS'), (None, 'LBRACKET'), (None, 'RBRACKET'), (None, 'LNCB'), (None, 'RNCB'), (None, 'NOT'), (None, 'AND'), (None, 'COMMA'), (None, 'INN'), (None, 'GR'), (None, 'LS'), (None, 'DIV'), (None, 'PRIME'), (None, 'SEMI'), (None, 'TRANSPOSE')])]}
_lexstateignore = {'INITIAL': ' \r\t'}
_lexstateerrorf = {'INITIAL': 't_error'}
